"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Course={id:string;code:string;name:string};type Match={document_id:string;chunk_index:number;similarity:number;content:string};type Doc={id:string;title:string;file_path:string|null};
type Message={role:"user"|"assistant";content:string};
export default function Study(){
 const [courses,setCourses]=useState<Course[]>([]);const [courseId,setCourseId]=useState("");const [question,setQuestion]=useState("");const [answer,setAnswer]=useState("");const [matches,setMatches]=useState<Match[]>([]);const [docs,setDocs]=useState<Record<string,Doc>>({});const [loading,setLoading]=useState(false);const [error,setError]=useState("");const [chatId,setChatId]=useState("");const [messages,setMessages]=useState<Message[]>([]);
 useEffect(()=>{const sb=createClient();const params=new URLSearchParams(window.location.search);const initialCourse=params.get("course")||"";const initialChat=params.get("chat")||"";setCourseId(initialCourse);setChatId(initialChat);Promise.all([sb.from("courses").select("id,code,name").order("code"),initialChat?sb.from("study_messages").select("role,content").eq("chat_id",initialChat).order("created_at"):Promise.resolve({data:[],error:null} as any)]).then(([cr,mr])=>{if(cr.error)setError(cr.error.message);setCourses((cr.data??[]) as Course[]);if(mr.error)setError(mr.error.message);setMessages((mr.data??[]) as Message[]);});},[]);
 useEffect(()=>{if(matches.length===0)return;const ids=[...new Set(matches.map(m=>m.document_id))];createClient().from("documents").select("id,title,file_path").in("id",ids).then(({data})=>{const map:Record<string,Doc>={};for(const d of (data??[]) as Doc[])map[d.id]=d;setDocs(map);});},[matches]);
 async function saveMessage(id:string,role:"user"|"assistant",content:string){const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from("study_messages").insert({chat_id:id,user_id:user.id,role,content});}
 async function ensureChat(firstQuestion:string){if(chatId)return chatId;const sb=createClient();const {data:{user}}=await sb.auth.getUser();if(!user)throw new Error("Sign in required.");const title=firstQuestion.length>60?firstQuestion.slice(0,60)+"…":firstQuestion;const {data,error}=await sb.from("study_chats").insert({user_id:user.id,title}).select("id").single();if(error)throw error;setChatId(data.id);window.history.replaceState(null,"","/study?chat="+data.id+(courseId?"&course="+courseId:""));return data.id;}
 async function ask(e?:React.FormEvent){e?.preventDefault();if(!question.trim()||loading)return;const q=question.trim();setLoading(true);setError("");setAnswer("");setMatches([]);try{const id=await ensureChat(q);setMessages(prev=>[...prev,{role:"user",content:q}]);await saveMessage(id,"user",q);const supabase=createClient();const {data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/study",{method:"POST",headers:{"Content-Type":"application/json",...(session?.access_token?{Authorization:"Bearer "+session.access_token}: {})},body:JSON.stringify({question:q,course_id:courseId||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Study request failed");setAnswer(d.answer);setMatches(d.matches||[]);setMessages(prev=>[...prev,{role:"assistant",content:d.answer}]);await saveMessage(id,"assistant",d.answer);await supabase.from("study_chats").update({updated_at:new Date().toISOString()}).eq("id",id);setQuestion("");}catch(e){setError(e instanceof Error?e.message:"Something went wrong");}finally{setLoading(false);}}
 async function openPdf(path:string|null){if(!path)return;const {data,error}=await createClient().storage.from("course-material").createSignedUrl(path,3600);if(error)setError(error.message);else if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener,noreferrer");}
 async function signOut(){await createClient().auth.signOut();window.location.href="/";}
 function onKeyDown(e:React.KeyboardEvent<HTMLTextAreaElement>){if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void ask();}}
 return <main className="app-shell"><aside className="sidebar"><div className="side-brand"><img className="brand-logo small-mark" src="/logo.svg" alt="University OS"/>University OS</div><nav><a href="/dashboard">Dashboard</a><a className="nav-active" href="/study">AI Study Assistant</a><a href="/courses">Courses</a><a href="/documents">Documents</a><a href="/chats">Chats</a><a href="/assignments">Assignments</a><a href="/exams">Exams</a></nav><div className="sidebar-note"><strong>Knowledge layer</strong><span>11 embedded chunks</span><small>Course material is retrieved before every answer.</small></div></aside><section className="workspace"><header className="topbar"><div><h1>AI Study Assistant</h1></div><div className="top-actions"><a className="ghost action-link" href="/chats">Chat history</a><button className="ghost" onClick={signOut}>Sign out</button></div></header><div className="study-grid"><section className="chat-panel"><div className="chat-intro"><span className="status-dot"/><div><strong>Grounded study mode</strong><p>Ask about indexed university material.</p></div></div>{messages.length>0?<div className="message-list">{messages.map((m,i)=><div className={"message "+m.role} key={i}><div className="message-bubble">{m.content}</div></div>)}</div>:<div className="empty-state"><div className="empty-icon">?</div><h2>What are you studying?</h2><p>Ask a question and Gemini will answer from your indexed course material.</p></div>}{error&&<div className="error">{error}</div>}<form onSubmit={ask} className="ask-box"><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">All courses</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select><div className="composer"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={onKeyDown} placeholder="Message University OS…" rows={1}/><button className="send-button" disabled={loading||!question.trim()} aria-label="Send">{loading?"…":"↑"}</button></div><div className="ask-footer"><span className="muted small">Enter to send · Shift+Enter for a new line</span></div></form></section><aside className="sources-panel"><div className="panel-heading">Sources <span className="count">{matches.length}</span></div>{matches.length===0?<p className="muted small">Sources used for an answer will appear here.</p>:matches.map((m,i)=><article className="source-card" key={m.document_id+"-"+m.chunk_index}><div className="source-top"><span>Source {i+1}</span><b>{Math.round(m.similarity*100)}%</b></div>{docs[m.document_id]?<button className="source-link" onClick={()=>openPdf(docs[m.document_id].file_path)}><span className="pdf-badge">PDF</span><span>{docs[m.document_id].title}</span><span>↗</span></button>:<p className="muted small">Loading document…</p>}<small>Relevant chunk {m.chunk_index}</small></article>)}</aside></div></section></main>;
}
