"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Course={id:string;code:string;name:string}; type Match={document_id:string;chunk_index:number;similarity:number;content:string};
export default function Study(){
 const [courses,setCourses]=useState<Course[]>([]); const [courseId,setCourseId]=useState(""); const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState(""); const [matches,setMatches]=useState<Match[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{createClient().from("courses").select("id,code,name").order("code").then(({data,error})=>{if(error)setError(error.message);setCourses((data??[]) as Course[]);});},[]);
 async function ask(e:React.FormEvent){e.preventDefault();if(!question.trim())return;setLoading(true);setError("");setAnswer("");setMatches([]);try{const supabase=createClient();const {data:{session}}=await supabase.auth.getSession();const r=await fetch("/api/study",{method:"POST",headers:{"Content-Type":"application/json",...(session?.access_token?{Authorization:"Bearer "+session.access_token}:{})},body:JSON.stringify({question,course_id:courseId||undefined})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Study request failed");setAnswer(d.answer);setMatches(d.matches||[]);}catch(e){setError(e instanceof Error?e.message:"Something went wrong");}finally{setLoading(false);}}
 async function signOut(){await createClient().auth.signOut();window.location.href="/";}
 return <main className="app-shell"><aside className="sidebar"><div className="side-brand"><span className="brand-mark small-mark">U</span>University OS</div><nav><a className="nav-active">AI Study Assistant</a><a href="/courses">Courses</a><a href="/documents">Documents</a><a href="/assignments">Assignments</a><a href="/exams">Exams</a></nav><div className="sidebar-note"><strong>Knowledge layer</strong><span>11 embedded chunks</span><small>Retrieved material is shown with each answer.</small></div></aside><section className="workspace"><header className="topbar"><div><p className="eyebrow">STUDY</p><h1>AI Study Assistant</h1></div><button className="ghost" onClick={signOut}>Sign out</button></header><div className="study-grid"><section className="chat-panel"><div className="chat-intro"><span className="status-dot"/> <div><strong>Grounded study mode</strong><p>Ask about indexed university material.</p></div></div>{answer?<div className="answer"><div className="answer-label">ANSWER</div><p>{answer}</p></div>:<div className="empty-state"><div className="empty-icon">?</div><h2>What are you studying?</h2><p>Retrieve relevant document chunks, then generate a grounded answer.</p></div>}{error&&<div className="error">{error}</div>}<form onSubmit={ask} className="ask-box"><select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">All courses</option>{courses.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask a question about your course material…" rows={4}/><div className="ask-footer"><span className="muted small">Retrieval → context → answer</span><button className="primary" disabled={loading}>{loading?"Thinking…":"Ask assistant"}</button></div></form></section><aside className="sources-panel"><div className="panel-heading">Retrieved sources <span className="count">{matches.length}</span></div>{matches.length===0?<p className="muted small">Sources used for an answer will appear here.</p>:matches.map((m,i)=><article className="source-card" key={m.document_id+"-"+m.chunk_index}><div className="source-top"><span>Source {i+1}</span><b>{Math.round(m.similarity*100)}%</b></div><p>{m.content}</p><small>Chunk {m.chunk_index}</small></article>)}</aside></div></section></main>;
}
