"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Course={id:string;code:string;name:string};
export default function Courses(){
 const [courses,setCourses]=useState<Course[]>([]);const [error,setError]=useState("");
 useEffect(()=>{async function load(){const {data,error}=await createClient().from("courses").select("id,code,name").order("code");if(error)setError(error.message);setCourses((data??[]) as Course[]);}void load();},[]);
 return <main className="app-shell"><aside className="sidebar"><div className="side-brand"><img className="brand-logo small-mark" src="/logo.svg" alt="University OS"/>University OS</div><nav><a href="/dashboard">Dashboard</a><a href="/study">AI Study Assistant</a><a className="nav-active" href="/courses">Courses</a><a href="/documents">Documents</a><a href="/chats">Chats</a><a href="/assignments">Assignments</a><a href="/exams">Exams</a></nav></aside><section className="workspace"><header className="topbar"><h1>Courses</h1><a className="ghost action-link" href="/dashboard">Dashboard</a></header><div className="dashboard">{error&&<div className="error">{error}</div>}<section className="folder-tree course-browser"><details className="tree-details" open><summary className="folder-root"><span className="folder-chevron">▾</span><span className="folder-symbol">▰</span><strong>First Semester</strong><span className="muted small">{courses.length} courses</span></summary><div className="semester-list">{courses.map(c=><div className="course-row" key={c.id}><span className="folder-symbol course-symbol">▱</span><div className="course-info"><strong>{c.code}</strong><span>{c.name}</span></div><a className="course-study-link" href={"/study?course="+c.id}>Study →</a></div>)}</div></details></section></div></section></main>;
}
