"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Course={id:string;code:string;name:string};type Doc={id:string;title:string;course_id:string|null;file_path:string|null;document_type:string|null};
export default function Documents(){
 const [courses,setCourses]=useState<Course[]>([]);const [docs,setDocs]=useState<Doc[]>([]);const [error,setError]=useState("");
 useEffect(()=>{const sb=createClient();Promise.all([sb.from("courses").select("id,code,name").order("code"),sb.from("documents").select("id,title,course_id,file_path,document_type").order("title")]).then(([cr,dr])=>{if(cr.error||dr.error)setError((cr.error||dr.error)?.message||"Could not load documents.");setCourses((cr.data??[]) as Course[]);setDocs((dr.data??[]) as Doc[]);});},[]);
 async function openPdf(path:string|null){if(!path)return;const {data,error}=await createClient().storage.from("course-material").createSignedUrl(path,3600);if(error)setError(error.message);else if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener,noreferrer");}
 return <main className="app-shell"><aside className="sidebar"><div className="side-brand"><img className="brand-logo small-mark" src="/logo.svg" alt="University OS"/>University OS</div><nav><a href="/dashboard">Dashboard</a><a href="/study">AI Study Assistant</a><a href="/courses">Courses</a><a className="nav-active" href="/documents">Documents</a><a href="/chats">Chats</a><a href="/assignments">Assignments</a><a href="/exams">Exams</a></nav></aside><section className="workspace"><header className="topbar"><h1>Documents</h1><a className="ghost action-link" href="/study">Study</a></header><div className="dashboard">{error&&<div className="error">{error}</div>}<section className="folder-tree document-browser"><details className="tree-details" open><summary className="folder-root"><span className="folder-chevron">▾</span><span className="folder-symbol">▰</span><strong>First Semester</strong><span className="muted small">{courses.length} courses</span></summary><div className="semester-list">{courses.map(c=>{const cd=docs.filter(d=>d.course_id===c.id);return <details className="course-folder" key={c.id}><summary className="folder-row course-folder-summary"><span className="folder-chevron">▾</span><span className="folder-symbol">▰</span><strong>{c.code}</strong><span className="muted small">{c.name}</span><span className="muted small">{cd.length}</span></summary><div className="folder-sub"><details className="tree-details document-details" open><summary className="folder-row document-folder"><span className="folder-chevron">▾</span><span className="folder-symbol">▰</span><strong>Documents</strong><span className="muted small">{cd.length}</span></summary><div>{cd.map(d=><button className="file-row" key={d.id} onClick={()=>openPdf(d.file_path)}><span className="pdf-badge">PDF</span><span>{d.title}</span><span className="file-open">Open ↗</span></button>)}{cd.length===0&&<div className="empty-folder">No documents yet.</div>}</div></details><div className="future-folder-row"><span className="folder-symbol">▰</span><span>Assignments</span><span>Quizzes</span><span>Presentations</span></div></div></details>})}</div></details></section></div></section></main>;
}
