"use client";
import { useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
export default function Dashboard(){
 const [counts,setCounts]=useState({courses:0,assignments:0,exams:0,documents:0});const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{async function load(){const supabase=createClient();const [{count:cc,error:ce},{count:ac,error:ae},{count:ec,error:ee},{count:dc,error:de}]=await Promise.all([supabase.from("courses").select("id",{count:"exact",head:true}),supabase.from("assignments").select("id",{count:"exact",head:true}),supabase.from("exams").select("id",{count:"exact",head:true}),supabase.from("documents").select("id",{count:"exact",head:true})]);if(ce||ae||ee||de)setError((ce||ae||ee||de)?.message||"Could not load dashboard.");setCounts({courses:cc??0,assignments:ac??0,exams:ec??0,documents:dc??0});setLoading(false);}load();},[]);
 async function signOut(){await createClient().auth.signOut();window.location.href="/";}
 return <main className="app-shell"><aside className="sidebar"><div className="side-brand"><span className="brand-mark small-mark">U</span>University OS</div><nav><a className="nav-active" href="/dashboard">Dashboard</a><a href="/study">AI Study Assistant</a><a href="/courses">Courses</a><a href="/documents">Documents</a><a href="/chats">Chats</a><a href="/assignments">Assignments</a><a href="/exams">Exams</a></nav></aside><section className="workspace"><header className="topbar"><div><h1>Dashboard</h1></div><button className="ghost" onClick={signOut}>Sign out</button></header><div className="dashboard">{error&&<div className="error">{error}</div>}<section className="welcome"><div><h2>Your university workspace</h2><p className="muted">Track your courses, material, deadlines and study sessions from one place.</p></div><a className="primary action-link" href="/study">Open Study Assistant</a></section><section className="stat-grid"><a className="stat-card" href="/courses"><span>Courses</span><strong>{loading?"—":counts.courses}</strong><small>Active semester</small></a><a className="stat-card" href="/documents"><span>Documents</span><strong>{loading?"—":counts.documents}</strong><small>Indexed materials</small></a><a className="stat-card" href="/assignments"><span>Assignments</span><strong>{loading?"—":counts.assignments}</strong><small>Tracked work</small></a><a className="stat-card" href="/exams"><span>Exams</span><strong>{loading?"—":counts.exams}</strong><small>Scheduled exams</small></a></section></div></section></main>;
}
